export const grades: number[] = Array.from({ length: 11 }, (_, i) => i + 1)

export const subjectsByClass: Record<number, string[]> = {
  1: [
    "Ona tili va o‘qish savodxonligi",
    "Matematika",
    "Tabiatshunoslik",
    "Ingliz tili",
    "Tasviriy san’at",
    "Texnologiya",
    "Musiqa",
    "Jismoniy tarbiya",
  ],
  2: [
    "Ona tili va o‘qish savodxonligi",
    "Matematika",
    "Tabiatshunoslik",
    "Ingliz tili",
    "Tasviriy san’at",
    "Texnologiya",
    "Musiqa",
    "Jismoniy tarbiya",
  ],
  3: [
    "Ona tili va o‘qish savodxonligi",
    "Matematika",
    "Tabiatshunoslik",
    "Ingliz tili",
    "Tasviriy san’at",
    "Texnologiya",
    "Musiqa",
    "Jismoniy tarbiya",
  ],
  4: [
    "Ona tili va o‘qish savodxonligi",
    "Matematika",
    "Tabiatshunoslik",
    "Ingliz tili",
    "Tasviriy san’at",
    "Texnologiya",
    "Musiqa",
    "Jismoniy tarbiya",
  ],
  5: [
    "Ona tili",
    "Adabiyot",
    "Matematika",
    "Tarix",
    "Geografiya",
    "Biologiya",
    "Informatika",
    "Ingliz tili",
    "Tasviriy san’at",
    "Texnologiya",
    "Musiqa",
    "Jismoniy tarbiya",
  ],
  6: [
    "Ona tili",
    "Adabiyot",
    "Matematika",
    "Tarix",
    "Geografiya",
    "Biologiya",
    "Informatika",
    "Ingliz tili",
    "Tasviriy san’at",
    "Texnologiya",
    "Musiqa",
    "Jismoniy tarbiya",
  ],
  7: [
    "Ona tili",
    "Adabiyot",
    "Algebra",
    "Geometriya",
    "Fizika",
    "Kimyo",
    "Biologiya",
    "Tarix",
    "Geografiya",
    "Informatika",
    "Ingliz tili",
    "Jismoniy tarbiya",
  ],
  8: [
    "Ona tili",
    "Adabiyot",
    "Algebra",
    "Geometriya",
    "Fizika",
    "Kimyo",
    "Biologiya",
    "Tarix",
    "Geografiya",
    "Informatika",
    "Ingliz tili",
    "Jismoniy tarbiya",
  ],
  9: [
    "Ona tili",
    "Adabiyot",
    "Algebra",
    "Geometriya",
    "Fizika",
    "Kimyo",
    "Biologiya",
    "Tarix",
    "Geografiya",
    "Informatika",
    "Ingliz tili",
    "Jismoniy tarbiya",
  ],
  10: [
    "Ona tili va adabiyot",
    "Algebra va analiz asoslari",
    "Geometriya",
    "Fizika",
    "Kimyo",
    "Biologiya",
    "O‘zbekiston tarixi",
    "Jahon tarixi",
    "Geografiya",
    "Informatika",
    "Ingliz tili",
    "Iqtisodiy bilim asoslari",
    "Huquq asoslari",
    "Jismoniy tarbiya",
  ],
  11: [
    "Ona tili va adabiyot",
    "Algebra va analiz asoslari",
    "Geometriya",
    "Fizika",
    "Kimyo",
    "Biologiya",
    "O‘zbekiston tarixi",
    "Jahon tarixi",
    "Geografiya",
    "Informatika",
    "Ingliz tili",
    "Iqtisodiy bilim asoslari",
    "Huquq asoslari",
    "Jismoniy tarbiya",
  ],
}
